$gitAliases = @{
    a       = '!git add . && git status'
    aa      = '!git add . && git add -u . && git status'
    ac      = '!git add . && git commit'
    acm     = '!git add . && git commit -m'
    alias   = '!git config --get-regexp ''^alias\.'' | sort'
    amend   = '!git add -A && git commit --amend --no-edit'
    au      = '!git add -u . && git status'
    b       = 'branch'
    ba      = 'branch --all'
    bclean  = '!f() { git branch --merged `${1-master} | grep -v " `${1-master}$" | xargs git branch -d; }; f'
    bdel    = '!f() { git branch -d `$1 && git push --delete `${2-origin} `$1; }; f'
    bdelf   = '!f() { git branch -D `$1 && git push --delete `${2-origin} `$1; }; f'
    bdelo   = '!f() { git push --delete `${2-origin} `$1; }; f'
    bdone   = '!f() { git checkout `${1-master} && git up && git bclean `${1-master}; }; f'
    c       = 'commit'
    ca      = 'commit --amend # careful'
    caamp    = '!f() { git add . && git commit -am \`"`$1\`" && git push; }; f'
    cam     = 'commit -am'
    cammp   = '!f() { git commit -am \`"`$1\`" -m \`"`$2\`" && git push; }; f'
    camp    = '!f() { git commit -am \`"`$1\`" && git push; }; f'
    cm      = 'commit -m'
    co      = 'checkout'
    cob     = 'checkout -b'
    con     = '!git --no-pager config --list'
    conl    = '!git --no-pager config --local --list'
    conls   = '!git --no-pager config --local --list --show-origin'
    cons    = '!git --no-pager config --list --show-origin'
    current = '!git branch | grep \* | cut -d '' '' -f2'
    d       = '!git --no-pager diff'
    dev     = 'checkout dev'
    dm      = '!git --no-pager diff --stat --color master'
    dmf     = '!git --no-pager diff --color master'
    f       = 'fetch --all'
    fp      = 'fetch --all --prune'
    fresh   = '!f() { git checkout -b `$1 && git push -u origin `$1; }; f'
    l       = 'log --graph --all --pretty=format:''%C(yellow)%h%C(cyan)%d%Creset %s %C(white)- %an, %ar%Creset'''
    lg      = 'log --color --graph --pretty=format:''%C(bold white)%h%Creset -%C(bold green)%d%Creset %s %C(bold green)(%cr)%Creset %C(bold blue)<%an>%Creset'' --abbrev-commit --date=relative'
    ll      = 'log --stat --abbrev-commit'
    llg     = 'log --color --graph --pretty=format:''%C(bold white)%H %d%Creset%n%s%n%+b%C(bold blue)%an <%ae>%Creset %C(bold green)%cr (%ci)'' --abbrev-commit'
    master  = 'checkout master'
    n       = 'checkout -b'
    origin  = 'remote get-url origin'
    p       = '!git push'
    pf      = '!git push -f'
    pu      = '!git push -u origin `$(git branch | grep \* | cut -d '' '' -f2)'
    s       = 'status'
    save    = '!git add -A && git commit -m ''SAVEPOINT'''
    ss      = 'status -s'
    stg     = 'checkout stg'
    syncup  = '!git fetch upstream && git checkout master && git merge upstream/master'
    up      = '!git pull --rebase --prune $@ && git submodule update --init --recursive'
    wip     = '!git add -u && git commit -m ''WIP'''
    wipe    = '!git add -A && git commit -qm ''WIPE SAVEPOINT'' && git reset HEAD~1 --hard'
}

Add-PSProfilePlugin -Name 'PSProfile.GitAliases' -ArgumentList $gitAliases -Save -Verbose
