AWSTemplateFormatVersion: '2010-09-09'
Description: Core Web Tier PRODUCTION
Resources:
  StdS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: MyBucket_Prd
      Tags:
        - Key: Name
          Value: cf-web-1
        - Key: Department
          Value: technology
        - Key: Environment
          Value: production
        - Key: Application
          Value: MyCoolWebApp
        - Key: Division
          Value: infrastructure
        - Key: Role
          Value: web
      AccessControl: BucketOwnerFullControl
  StdEC2Role:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      Policies:
        - PolicyName: DefaultEC2Policy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Resource:
                  - '*'
                Action:
                  - logs:CreateLogStream
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                  - logs:PutLogEvents
              - Effect: Allow
                Condition:
                  StringEquals:
                    ec2:ResourceTag/aws:cloudformation:stack-name: web-tier-core-prd
                Resource:
                  - '*'
                Action:
                  - ec2:CreateTags
                  - ec2:DeleteTags
                  - ec2:DescribeTags
              - Effect: Allow
                Resource:
                  - !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - MyBucket_Prd
                  - !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - MyBucket_Prd
                      - /*
                Action:
                  - s3:Get*
                  - s3:List*
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentAdminPolicy
  StdEC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref 'StdEC2Role'
  StdS3Policy:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - !Ref 'StdEC2Role'
      PolicyDocument:
        Statement:
          - Effect: Allow
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - MyBucket_Prd
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - MyBucket_Prd
                  - /*
            Action:
              - s3:DeleteObject
              - s3:GetObject
              - s3:ListBucket
              - s3:PutObject
      PolicyName: StdS3Policy
  StdPRDMonitoringTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Join
        - ''
        - - Monitoring_Environment-
          - prd
          - _Application-
          - web-tier-core
      Subscription:
        - Endpoint: !Join
            - ''
            - - 'arn:aws:sqs:'
              - !Ref 'AWS::Region'
              - ':'
              - !Ref 'AWS::AccountId'
              - MonitoringQueue
          Protocol: sqs
  StdPRDMonitoringHostTemplate:
    Type: Custom::MonitoringHostTemplate
    Properties:
      HostTemplateName: web-tier-core-prd
      ServiceToken: !Join
        - ''
        - - 'arn:aws:sns:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - MonitoringHostTemplateTopic
      AccountId: !Ref 'AWS::AccountId'
      HostTemplateDescription: Host template for web-tier-core-prd stack.
  StdElasticLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      HealthCheck:
        Target: HTTPS:443/healthcheck.htm
        HealthyThreshold: '2'
        UnhealthyThreshold: '2'
        Interval: '12'
        Timeout: '10'
      SecurityGroups:
        - !ImportValue 'webserver-sec-group'
      Subnets:
        - !ImportValue 'subnet-web-front-end-us-west-2a'
        - !ImportValue 'subnet-web-front-end-us-west-2b'
      LoadBalancerName: !Join
        - '-'
        - - web-tier-core
          - prd
      Tags:
        - Key: Name
          Value: cf-web-1
        - Key: Department
          Value: technology
        - Key: Environment
          Value: production
        - Key: Application
          Value: MyCoolWebApp
        - Key: Division
          Value: infrastructure
        - Key: Role
          Value: web
      Scheme: Internal
      Listeners:
        - LoadBalancerPort: '80'
          InstancePort: '80'
          InstanceProtocol: HTTP
          Protocol: HTTP
        - LoadBalancerPort: '443'
          InstancePort: '443'
          InstanceProtocol: TCP
          Protocol: TCP
      CrossZone: true
      ConnectionDrainingPolicy:
        Enabled: true
        Timeout: 300
  StdLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      UserData: !Base64
        Fn::Join:
          - ''
          - - <powershell>
            - param(
            - "\t$stackname = 'web-tier-core',"
            - "\t$region = 'us-west-2'"
            - )
            - $flagsDir = "C:\Flags"
            - $cfnSignalFlag = Join-Path $flagsDir "cfn-signal.flag"
            - if (!(Test-Path $flagsDir)) {
            - "\tNew-Item -Path $flagsDir -ItemType Directory"
            - '}'
            - $name = "WIN-$((Get-NetAdapter | Select-Object -First 1).MacAddress.Replace('-','').SubString(1,11))"
            - if ($env:COMPUTERNAME -ne $name) {
            - "\tRename-Computer $name -Force -Restart"
            - '}'
            - elseif ($env:USERDOMAIN -eq $env:COMPUTERNAME) {
            - '}'
            - elseif (!(Test-Path $cfnSignalFlag)) {
            - "\t& cfn-signal.exe -e 0 --resource AutoScalingGroup --stack $stackname\
              \ --region $region"
            - "\tNew-Item -Path $cfnSignalFlag -ItemType File"
            - '}'
            - </powershell>
      IamInstanceProfile: !Ref 'StdEC2InstanceProfile'
      ImageId: ami-f582359e
      SecurityGroups:
        - !ImportValue 'monitorpatching-sec-group'
        - !ImportValue 'windowsmanagement-sec-group'
        - !ImportValue 'ad-sec-group'
        - !ImportValue 'webserver-sec-group'
      KeyName: WindowsPrd
      InstanceType: t2.large
  StdAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        - us-west-2a
        - us-west-2b
      NotificationConfigurations:
        - NotificationTypes:
            - autoscaling:EC2_INSTANCE_LAUNCH
            - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
            - autoscaling:EC2_INSTANCE_TERMINATE
            - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
          TopicARN: !Ref 'StdPRDMonitoringTopic'
      LoadBalancerNames:
        - !Ref 'StdElasticLoadBalancer'
      HealthCheckType: EC2
      DesiredCapacity: '4'
      LaunchConfigurationName: !Ref 'StdLaunchConfiguration'
      MaxSize: '4'
      VPCZoneIdentifier:
        - !ImportValue 'subnet-web-front-end-us-west-2a'
        - !ImportValue 'subnet-web-front-end-us-west-2b'
      MinSize: '2'
      Tags:
        - Key: Name
          Value: cf-web-1
          PropagateAtLaunch: true
        - Key: Department
          Value: technology
          PropagateAtLaunch: true
        - Key: Environment
          Value: production
          PropagateAtLaunch: true
        - Key: Application
          Value: MyCoolWebApp
          PropagateAtLaunch: true
        - Key: Division
          Value: infrastructure
          PropagateAtLaunch: true
        - Key: Role
          Value: web
          PropagateAtLaunch: true
    CreationPolicy:
      AutoScalingCreationPolicy:
        MinSuccessfulInstancesPercent: '100'
      ResourceSignal:
        Count: '4'
        Timeout: PT1H
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: '2'
        MaxBatchSize: '2'
        SuspendProcesses:
          - HealthCheck
          - ReplaceUnhealthy
          - AZRebalance
          - AlarmNotification
          - ScheduledActions
        WaitOnResourceSignals: 'true'
        PauseTime: PT1H
  StdElbDnsEntry:
    Type: Custom::DNSEntry
    Properties:
      RecordName: web-tier-core-prd
      RecordData: !GetAtt 'StdElasticLoadBalancer.DNSName'
      ServiceToken: !ImportValue 'dns-entry-sns-arn'
